#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Cookie-Baker
Version  : 0.09
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/K/KA/KAZEBURO/Cookie-Baker-0.09.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/K/KA/KAZEBURO/Cookie-Baker-0.09.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libc/libcookie-baker-perl/libcookie-baker-perl_0.09-1.debian.tar.xz
Summary  : 'Cookie string generator / parser'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Cookie-Baker-license
Requires: perl-Cookie-Baker-man
BuildRequires : perl(ExtUtils::Config)
BuildRequires : perl(ExtUtils::Helpers)
BuildRequires : perl(ExtUtils::InstallPaths)
BuildRequires : perl(Module::Build::Tiny)

%description
# NAME
Cookie::Baker - Cookie string generator / parser
# SYNOPSIS
use Cookie::Baker;

%package license
Summary: license components for the perl-Cookie-Baker package.
Group: Default

%description license
license components for the perl-Cookie-Baker package.


%package man
Summary: man components for the perl-Cookie-Baker package.
Group: Default

%description man
man components for the perl-Cookie-Baker package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Cookie-Baker-0.09
mkdir -p %{_topdir}/BUILD/Cookie-Baker-0.09/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Cookie-Baker-0.09/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Cookie-Baker
cp LICENSE %{buildroot}/usr/share/doc/perl-Cookie-Baker/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Cookie/Baker.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Cookie-Baker/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Cookie::Baker.3
